Repository vtex/shoreline, pull requests merged in 2022-07, with the labels that each got.

#274 docs(data-grid): remove preview code live mode
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/data-grid.mdx
Labels: 🐛 bug, 📚 documentation

#281 refactor: update menu labels typing to ReactNode
  packages/admin-ui/src/menu/menu-button.tsx
  packages/admin-ui/src/menu/menu-item.tsx
Labels: 🧹 refactoring

#278 docs(table): update overview and code tabs content
  packages/admin-ui-docs/content/table/code.mdx
  packages/admin-ui-docs/content/table/overview.mdx
Labels: 📚 documentation

#280 Refactor/remove density variants
  packages/admin-ui-docs/content/table/code.mdx
  packages/admin-ui/src/table/components/table-body.tsx
  packages/admin-ui/src/table/components/table-cell.tsx
  packages/admin-ui/src/table/components/table-head.tsx
  packages/admin-ui/src/table/hooks/use-table-state.tsx
  packages/admin-ui/src/table/resolvers/image.tsx
  packages/admin-ui/src/table/resolvers/resolver-core.tsx
  packages/admin-ui/src/table/resolvers/text.tsx
  packages/admin-ui/src/table/styles/table-cell.styles.ts
  packages/admin-ui/src/table/tests/resolverCore.test.tsx
  packages/admin-ui/src/table/tests/resolvers.test.tsx
  packages/admin-ui/src/table/types.tsx
Labels: 🧹 refactoring, 🚨 breaking change

#296 docs: update section space between
  packages/admin-ui-docs/src/components/Section/styles.scss
Labels: 📚 documentation

#298 fix(alert): update icon margin style
  packages/admin-ui/src/alert/alert.tsx
Labels: 🧹 refactoring

#300 docs(form): add some content about the use of useFormState with some …
  packages/admin-ui-docs/content/form/code.mdx
  packages/admin-ui-docs/content/form/overview.mdx
Labels: 📚 documentation

#302 fix(set): remove deprecated set component
  packages/admin-ui-docs/docs/guidelines/components/alert.mdx
  packages/admin-ui-docs/docs/guidelines/components/avatar.mdx
  packages/admin-ui-docs/docs/guidelines/components/card.mdx
  packages/admin-ui-docs/docs/guidelines/components/collapsible-group.mdx
  packages/admin-ui-docs/docs/guidelines/components/divider.mdx
  packages/admin-ui-docs/docs/guidelines/components/dropdown.mdx
  packages/admin-ui-docs/docs/guidelines/components/heading.mdx
  packages/admin-ui-docs/docs/guidelines/components/set.mdx
  packages/admin-ui-docs/docs/guidelines/components/spinner.mdx
  packages/admin-ui-docs/docs/guidelines/components/switch.mdx
  packages/admin-ui-docs/docs/guidelines/experimental/combobox.mdx
  packages/admin-ui-docs/docs/introduction/developing/migrating.mdx
  packages/admin-ui-docs/src/components/IconsGrid/index.tsx
  packages/admin-ui-docs/src/components/TokensTable/tokens.tsx
  packages/admin-ui-docs/src/components/Typeface.tsx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/alert.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/avatar.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/card.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/collapsible-group.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/data-grid.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/divider.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/dropdown.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/heading.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/input-password.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/input.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/numeric-stepper.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/select.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/set.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/spinner.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/switch.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/text-area.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/tooltip.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/experimental/combobox.mdx
  packages/admin-ui-docs/versioned_docs/version-0.132.0/guidelines/components/alert.mdx
  packages/admin-ui-docs/versioned_docs/version-0.132.0/guidelines/components/avatar.mdx
  packages/admin-ui-docs/versioned_docs/version-0.132.0/guidelines/components/card.mdx
  packages/admin-ui-docs/versioned_docs/version-0.132.0/guidelines/components/collapsible-group.mdx
  packages/admin-ui-docs/versioned_docs/version-0.132.0/guidelines/components/divider.mdx
  packages/admin-ui-docs/versioned_docs/version-0.132.0/guidelines/components/dropdown.mdx
  packages/admin-ui-docs/versioned_docs/version-0.132.0/guidelines/components/heading.mdx
  packages/admin-ui-docs/versioned_docs/version-0.132.0/guidelines/components/set.mdx
  packages/admin-ui-docs/versioned_docs/version-0.132.0/guidelines/components/spinner.mdx
  packages/admin-ui-docs/versioned_docs/version-0.132.0/guidelines/components/switch.mdx
  packages/admin-ui-docs/versioned_docs/version-0.132.0/guidelines/experimental/combobox.mdx
  packages/admin-ui-react/README.md
  packages/admin-ui/src/deprecated-set/Set.stories.tsx
  packages/admin-ui/src/deprecated-set/Set.test.tsx
  packages/admin-ui/src/deprecated-set/index.tsx
  packages/admin-ui/src/index.ts
Labels: 🚨 breaking change

#311 fix(menu-button): add onClick to MenuButton props
  packages/admin-ui/src/menu/menu-button.tsx
Labels: 🐛 bug

#307 docs(page): update overriden defaults data
  packages/admin-ui-docs/content/page/code.mdx
  packages/admin-ui-docs/content/page/overview.mdx
  packages/admin-ui-docs/docs/guidelines/components/page.mdx
  packages/admin-ui-docs/versioned_docs/version-0.132.0/guidelines/components/page.mdx
  packages/admin-ui/src/page/page.stories.tsx
Labels: 📚 documentation

#321 fix(topbar): adjust skeleton space to be according with the design specs
  packages/admin-ui/src/components/Topbar/index.tsx
Labels: 🐛 bug

#324 fix(border): helper function to apply border style not working
  packages/admin-ui-core/src/__tests__/styles.test.ts
  packages/admin-ui-core/src/helpers.ts
  packages/admin-ui-core/src/styles.ts
Labels: 🐛 bug

#341 refactor(table): update structure and scroll behavior
  packages/admin-ui/src/table/components/table-body.tsx
  packages/admin-ui/src/table/components/table-cell.tsx
  packages/admin-ui/src/table/components/table-head.tsx
  packages/admin-ui/src/table/components/table.tsx
  packages/admin-ui/src/table/hooks/use-table-state.tsx
  packages/admin-ui/src/table/styles/table-body.styles.ts
  packages/admin-ui/src/table/styles/table-cell.styles.ts
  packages/admin-ui/src/table/styles/table-head.styles.ts
  packages/admin-ui/src/table/styles/table-row.styles.ts
  packages/admin-ui/src/table/styles/table.styles.ts
Labels: 🧹 refactoring

#342 docs(table): fix table in the code preview section
  packages/admin-ui-docs/content/table/overview.mdx
  packages/admin-ui-docs/src/components/Page/styles.scss
  packages/admin-ui-docs/src/css/markdown.scss
Labels: 🐛 bug, 📚 documentation
