Repository vtex/shoreline, pull requests merged in 2022-06, with the labels that each got.

#220 Rollback react version to 16.9.x and change ariakit version to 2.0.0-rc.22
  package.json
  packages/admin-ui-codemod/package.json
  packages/admin-ui-core/package.json
  packages/admin-ui-form/package.json
  packages/admin-ui-hooks/package.json
  packages/admin-ui-react/package.json
  packages/admin-ui-util/package.json
  packages/admin-ui/package.json
  packages/admin-ui/src/filters/__tests__/__snapshots__/filter-multiple.test.tsx.snap
  packages/admin-ui/src/filters/__tests__/__snapshots__/filter.test.tsx.snap
  packages/formik/package.json
  yarn.lock
Labels: 🐛 bug, 🔁 dependencies

#212 add messages translation
  packages/admin-ui/src/components/SearchBox/intl.tsx
Labels: 🌎 i18n

#208 Feat/automated release notes
  .github/release.yml
Labels: 💬 request for comments

#202 Add Select component review
  packages/admin-ui/src/form-control/form-control.tsx
  packages/admin-ui/src/next.ts
  packages/admin-ui/src/select/index.tsx
  packages/admin-ui/src/select/select-icon.tsx
  packages/admin-ui/src/select/select-input.tsx
  packages/admin-ui/src/select/select.i18n.tsx
  packages/admin-ui/src/select/select.styles.ts
  packages/admin-ui/src/select/select.tsx
  packages/admin-ui/src/select/stories/select.stories.tsx
  packages/admin-ui/src/select/tests/select.test.tsx
Labels: 🚨 breaking change

#201 Feat/nad 976 number field
  packages/admin-ui-docs/src/components/BestPractices.tsx
  packages/admin-ui-docs/src/components/PageSection/styles.scss
  packages/admin-ui/src/index.ts
  packages/admin-ui/src/number-input/__snapshots__/number-input.test.tsx.snap
  packages/admin-ui/src/number-input/index.ts
  packages/admin-ui/src/number-input/number-input.i18n.ts
  packages/admin-ui/src/number-input/number-input.state.ts
  packages/admin-ui/src/number-input/number-input.stories.tsx
  packages/admin-ui/src/number-input/number-input.style.ts
  packages/admin-ui/src/number-input/number-input.test.tsx
  packages/admin-ui/src/number-input/number-input.tsx
  packages/admin-ui/src/number-input/utils.ts
Labels: 📚 documentation, 🆕 feature

#215 NAD-865 - Tag component review
  packages/admin-ui-codemod/README.md
  packages/admin-ui-codemod/bin/cli.js
  packages/admin-ui-codemod/src/__tests__/tag-review.test.js
  packages/admin-ui-codemod/src/tag-review.js
  packages/admin-ui-docs/docs/guidelines/components/tag.mdx
  packages/admin-ui-docs/src/components/PageHeader/links.ts
  packages/admin-ui/src/bleed/bleed.stories.tsx
  packages/admin-ui/src/components/Tag/Tag.stories.tsx
  packages/admin-ui/src/components/Tag/Tag.test.tsx
  packages/admin-ui/src/components/Tag/index.tsx
  packages/admin-ui/src/components/Tooltip/__stories__/Tooltip.stories.tsx
  packages/admin-ui/src/index.ts
  packages/admin-ui/src/inline/inline.stories.tsx
  packages/admin-ui/src/tag/index.tsx
  packages/admin-ui/src/tag/tag.stories.tsx
  packages/admin-ui/src/tag/tag.style.ts
  packages/admin-ui/src/tag/tag.test.tsx
  packages/admin-ui/src/tag/tag.ts
Labels: 📚 documentation, 🚨 breaking change

#222 docs(code-styleguide): update to new specs
  packages/admin-ui-docs/docs/teams/developing/code-styleguide.mdx
Labels: 📚 documentation

#205 fix(admin-ui-form): improve compatibility w/ VTEX IO and fix typescript
  packages/admin-ui-form/package.json
  yarn.lock
Labels: 🐛 bug, 🗒 typescript

#232 docs(teams): merge teams section with introduction
  packages/admin-ui-docs/docs/introduction/contact-us.mdx
  packages/admin-ui-docs/docs/introduction/developing/_category_.json
  packages/admin-ui-docs/docs/introduction/developing/code-styleguide.mdx
  packages/admin-ui-docs/docs/introduction/developing/contributing.mdx
  packages/admin-ui-docs/docs/introduction/developing/hooks.mdx
  packages/admin-ui-docs/docs/introduction/developing/migrating.mdx
  packages/admin-ui-docs/docs/introduction/developing/quick-start.mdx
  packages/admin-ui-docs/docs/introduction/developing/styling.mdx
  packages/admin-ui-docs/docs/introduction/developing/tag.mdx
  packages/admin-ui-docs/docs/introduction/developing/theming.mdx
  packages/admin-ui-docs/docs/introduction/release-notes.mdx
  packages/admin-ui-docs/docs/teams/_category_.json
  packages/admin-ui-docs/docs/teams/contributing/_category_.json
  packages/admin-ui-docs/docs/teams/contributing/publishing.mdx
  packages/admin-ui-docs/docs/teams/developing/naming-conventions.mdx
Labels: 📚 documentation

#239 docs: add number-input documentation
  packages/admin-ui-docs/docs/guidelines/components/number-input.mdx
Labels: 📚 documentation

#241 fix: fix code preview container to show menu popover correctly
  packages/admin-ui-docs/src/components/CodePreviewContainer/index.tsx
Labels: 📚 documentation

#246 docs(admin-ui): disable live view for deprecated/removed components
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/input-password.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/input.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/numeric-stepper.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/select.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/text-area.mdx
Labels: 📚 documentation

#248 Feat/review menu
  packages/admin-ui/src/button/button.style.ts
  packages/admin-ui/src/index.ts
  packages/admin-ui/src/menu/index.ts
  packages/admin-ui/src/menu/menu-button.tsx
  packages/admin-ui/src/menu/menu-divider.tsx
  packages/admin-ui/src/menu/menu-item-wrapper.tsx
  packages/admin-ui/src/menu/menu-item.tsx
  packages/admin-ui/src/menu/menu.i18n.ts
  packages/admin-ui/src/menu/menu.state.ts
  packages/admin-ui/src/menu/menu.stories.tsx
  packages/admin-ui/src/menu/menu.style.ts
  packages/admin-ui/src/menu/menu.tsx
Labels: 🧹 refactoring, 🚨 breaking change

#254 docs(dx): improve dev experience when writing docs
  packages/admin-ui-docs/content/button/code.mdx
  packages/admin-ui-docs/content/button/design.mdx
  packages/admin-ui-docs/content/button/overview.mdx
  packages/admin-ui-docs/content/button/toc.js
  packages/admin-ui-docs/content/radio/code.mdx
  packages/admin-ui-docs/content/radio/design.mdx
  packages/admin-ui-docs/content/radio/overview.mdx
  packages/admin-ui-docs/content/radio/toc.js
  packages/admin-ui-docs/docs/guidelines/components/box.mdx
  packages/admin-ui-docs/docs/guidelines/components/checkbox.mdx
  packages/admin-ui-docs/docs/guidelines/components/number-input.mdx
  packages/admin-ui-docs/docs/guidelines/components/search.mdx
  packages/admin-ui-docs/docs/guidelines/components/stack.mdx
  packages/admin-ui-docs/docs/guidelines/components/switch.mdx
  packages/admin-ui-docs/docs/guidelines/components/tag.mdx
  packages/admin-ui-docs/src/components/IntroSection/index.tsx
  packages/admin-ui-docs/src/components/MultipleCodeSection/index.tsx
  packages/admin-ui-docs/src/components/Section/index.tsx
  packages/admin-ui-docs/src/components/Section/styles.scss
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/box.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/button.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/checkbox.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/radio.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/search.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/stack.mdx
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/switch.mdx
Labels: 📚 documentation

#262 docs: replace live editor with static code block in menu docs
  packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/menu.mdx
Labels: 📚 documentation

#258 docs(text-input): add docs page
  packages/admin-ui-docs/content/text-input/code.mdx
  packages/admin-ui-docs/content/text-input/design.mdx
  packages/admin-ui-docs/content/text-input/overview.mdx
  packages/admin-ui-docs/content/text-input/toc.js
  packages/admin-ui-docs/docs/guidelines/components/text-input.mdx
Labels: 📚 documentation

#260 docs(text-area): add docs page
  packages/admin-ui-docs/content/text-area/code.mdx
  packages/admin-ui-docs/content/text-area/design.mdx
  packages/admin-ui-docs/content/text-area/overview.mdx
  packages/admin-ui-docs/content/text-area/toc.js
  packages/admin-ui-docs/docs/guidelines/components/text-area.mdx
Labels: 📚 documentation

#237 NAD-866 - Alert component review
  packages/admin-ui-codemod/bin/cli.js
  packages/admin-ui-codemod/src/__tests__/alert-review.test.js
  packages/admin-ui-codemod/src/alert-review.js
  packages/admin-ui-docs/docs/guidelines/components/alert.mdx
  packages/admin-ui-util/src/types.ts
  packages/admin-ui/src/alert/alert.stories.tsx
  packages/admin-ui/src/alert/alert.style.ts
  packages/admin-ui/src/alert/alert.test.tsx
  packages/admin-ui/src/alert/alert.tsx
  packages/admin-ui/src/alert/index.tsx
  packages/admin-ui/src/components/Alert/__stories__/Alert.stories.tsx
  packages/admin-ui/src/components/Alert/__tests__/Alert.test.tsx
  packages/admin-ui/src/components/Alert/index.tsx
  packages/admin-ui/src/index.ts
Labels: 📚 documentation, 🚨 breaking change

#266 fix(checkbox): fix aria-checked value
  packages/admin-ui/src/checkbox/checkbox-input.tsx
Labels: 🐛 bug

#273 refactor: remove old menu content
  packages/admin-ui-docs/src/components/PageHeader/links.ts
  packages/admin-ui/src/components/DataView/__stories__/DataView.stories.tsx
  packages/admin-ui/src/components/FilterBar/components/Statement.tsx
  packages/admin-ui/src/components/FilterBar/components/StatementMenu.tsx
  packages/admin-ui/src/components/FilterBar/components/index.tsx
  packages/admin-ui/src/components/FilterBar/index.tsx
  packages/admin-ui/src/components/Menu/Menu.stories.tsx
  packages/admin-ui/src/components/Menu/Menu.style.ts
  packages/admin-ui/src/components/Menu/Menu.test.tsx
  packages/admin-ui/src/components/Menu/components/Menu.tsx
  packages/admin-ui/src/components/Menu/components/MenuButton.tsx
  packages/admin-ui/src/components/Menu/components/MenuContext.tsx
  packages/admin-ui/src/components/Menu/components/MenuItem.tsx
  packages/admin-ui/src/components/Menu/components/MenuList.tsx
  packages/admin-ui/src/components/Menu/components/MenuSeparator.tsx
  packages/admin-ui/src/components/Menu/index.ts
  packages/admin-ui/src/components/Menu/state.tsx
  packages/admin-ui/src/components/Toolbar/__stories__/Toolbar.stories.tsx
  packages/admin-ui/src/menu/menu.stories.tsx
  packages/admin-ui/src/menu/menu.tsx
Labels: 🧹 refactoring, 🚨 breaking change

#272 refactor: improve menu state wrapper and its typing
  packages/admin-ui/src/menu/menu.state.ts
Labels: 🧹 refactoring

#265 Refactor/table cell style
  packages/admin-ui/src/table/components/table-body.tsx
  packages/admin-ui/src/table/components/table-cell.tsx
  packages/admin-ui/src/table/components/table-head.tsx
  packages/admin-ui/src/table/hooks/use-table-sort.ts
  packages/admin-ui/src/table/hooks/use-table-state.tsx
  packages/admin-ui/src/table/resolvers/base.tsx
  packages/admin-ui/src/table/resolvers/image.tsx
  packages/admin-ui/src/table/resolvers/text.tsx
  packages/admin-ui/src/table/stories/clickable.stories.tsx
  packages/admin-ui/src/table/stories/selectable.stories.tsx
  packages/admin-ui/src/table/stories/sortable.stories.tsx
  packages/admin-ui/src/table/styles/table-body.styles.ts
  packages/admin-ui/src/table/styles/table-cell.styles.ts
  packages/admin-ui/src/table/styles/table-head.styles.ts
  packages/admin-ui/src/table/styles/table-row.styles.ts
Labels: 🧹 refactoring, 🆕 feature

#277 docs(table): update code tab
  packages/admin-ui-docs/content/table/code.mdx
  packages/admin-ui-docs/content/table/overview.mdx
  packages/admin-ui-docs/content/table/toc.js
  packages/admin-ui-docs/docs/guidelines/components/table.mdx
  packages/admin-ui-docs/src/components/CodePreviewContainer/styles.scss
Labels: 📚 documentation
