Repository vtex/shoreline, pull requests merged in 2022-02, with the labels that each got.

#14 fix(deps): change deps between internal packages
  packages/admin-ui-hooks/package.json
  packages/admin-ui-react/package.json
  packages/admin-ui/package.json
  packages/eslint-plugin-admin-ui/package.json
  packages/formik/package.json
Labels: 🐛 bug

#8 ci(circle): add circle ci workflow
  .circleci/config.yml
  package.json
  packages/admin-ui/package.json
Labels: 🤖 ci

#60 ci(circle): add chromatic job & workflow
  .circleci/config.yml
Labels: 🔁 dependencies, 🤖 ci

#61 build(phosphor-icons): bump icons to version 0.2.3
  packages/admin-ui-react/package.json
  packages/admin-ui/package.json
  yarn.lock
Labels: 🐛 bug, 🔥 performance

#58 fix(toast component): fix toast component width and position for mobile devices
  packages/admin-ui/src/components/Toast/components/ToastQueue.tsx
Labels: 🐛 bug
