Repository vtex/shoreline, pull requests merged in 2022-03, with the labels that each got.

#75 Datepicker update
  packages/admin-ui-docs/docs/experimental/date-picker.mdx
  packages/admin-ui/src/date-field/date-field.style.ts
  packages/admin-ui/src/date-field/date-field.tsx
  packages/admin-ui/src/date-picker/date-picker-calendar.tsx
  packages/admin-ui/src/date-picker/date-picker-field.tsx
  packages/admin-ui/src/date-picker/date-picker.state.ts
  packages/admin-ui/src/date-picker/date-picker.stories.tsx
  packages/admin-ui/src/date-picker/date-picker.tsx
  packages/admin-ui/src/date-picker/index.ts
  packages/admin-ui/src/experimental.ts
  packages/admin-ui/src/segment/segment.style.ts
Labels: 👻 experimental

#76 Add experimental combobox
  packages/admin-ui-docs/docs/experimental/combobox.mdx
  packages/admin-ui/package.json
  packages/admin-ui/src/combobox/combobox-field.tsx
  packages/admin-ui/src/combobox/combobox-item.ts
  packages/admin-ui/src/combobox/combobox-popover.tsx
  packages/admin-ui/src/combobox/combobox.i18n.ts
  packages/admin-ui/src/combobox/combobox.state.ts
  packages/admin-ui/src/combobox/combobox.stories.tsx
  packages/admin-ui/src/combobox/combobox.style.ts
  packages/admin-ui/src/combobox/index.ts
  packages/admin-ui/src/experimental.ts
  packages/admin-ui/src/i18n/index.ts
  packages/admin-ui/src/i18n/locales.ts
  packages/admin-ui/src/i18n/react-aria-i18n.ts
  yarn.lock
Labels: 👻 experimental

#77 Sidebar design & behavior improvements
  .storybook/preview.js
  packages/admin-ui-core/src/tokens/text.ts
  packages/admin-ui-core/src/values/typography.ts
  packages/admin-ui-react/src/createIcons.tsx
  packages/admin-ui/src/components/AbstractInput/__snapshots__/AbstractInput.test.tsx.snap
  packages/admin-ui/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
  packages/admin-ui/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/admin-ui/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/admin-ui/src/components/Collapsible/__tests__/__snapshots__/Collapsible.test.tsx.snap
  packages/admin-ui/src/components/CollapsibleGroup/__snapshots__/CollapsibleGroup.test.tsx.snap
  packages/admin-ui/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/admin-ui/src/components/FilterBar/__tests__/__snapshots__/FilterBar.test.tsx.snap
  packages/admin-ui/src/components/Input/__snapshots__/Input.test.tsx.snap
  packages/admin-ui/src/components/InputPassword/__snapshots__/InputPassword.test.tsx.snap
  packages/admin-ui/src/components/Menu/__snapshots__/Menu.test.tsx.snap
  packages/admin-ui/src/components/NumericStepper/__snapshots__/NumericStepper.test.tsx.snap
  packages/admin-ui/src/components/Page/__tests__/__snapshots__/PageHeader.test.tsx.snap
  packages/admin-ui/src/components/Search/__tests__/__snapshots__/Search.test.tsx.snap
  packages/admin-ui/src/components/Select/__snapshots__/Select.test.tsx.snap
  packages/admin-ui/src/components/Sidebar/__stories__/Sidebar.stories.tsx
  packages/admin-ui/src/components/Sidebar/components/Sidebar.tsx
  packages/admin-ui/src/components/Sidebar/components/SidebarBackdrop.tsx
  packages/admin-ui/src/components/Sidebar/components/SidebarDisclosure.tsx
  packages/admin-ui/src/components/Sidebar/components/SidebarItem.tsx
  packages/admin-ui/src/components/Sidebar/components/SidebarSection.tsx
  packages/admin-ui/src/components/Sidebar/components/SidebarSectionItem.tsx
  packages/admin-ui/src/components/Sidebar/hooks/useSidebarState.ts
  packages/admin-ui/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
  packages/admin-ui/src/components/Tag/__snapshots__/Tag.test.tsx.snap
  packages/admin-ui/src/components/Toast/__tests__/__snapshots__/Toast.test.tsx.snap
Labels: 👩🏼‍🎨 design needed

#80 fix(bundle-size): remove framer-motion dependency to reduce bundle size
  packages/admin-ui/package.json
  packages/admin-ui/src/components/SearchBox/index.tsx
  yarn.lock
Labels: 🔁 dependencies

#83 fix(font-preload): change url to the right one
  packages/admin-ui-react/src/createSystem.tsx
Labels: 🐛 bug, 🔥 performance

#96 fix(admin-ui-core): custom tokens not parsed by csx while nested
  packages/admin-ui-core/src/styles.ts
Labels: 🐛 bug

#79 Add ComboboxMultiple
  packages/admin-ui-docs/docs/experimental/combobox.mdx
  packages/admin-ui/src/combobox/combobox-multiple-field.tsx
  packages/admin-ui/src/combobox/combobox-multiple-item.tsx
  packages/admin-ui/src/combobox/combobox-multiple-popover.tsx
  packages/admin-ui/src/combobox/combobox-multiple-tag.tsx
  packages/admin-ui/src/combobox/combobox-multiple.state.ts
  packages/admin-ui/src/combobox/combobox-popover-base.tsx
  packages/admin-ui/src/combobox/combobox-popover.tsx
  packages/admin-ui/src/combobox/combobox.i18n.ts
  packages/admin-ui/src/combobox/combobox.state.ts
  packages/admin-ui/src/combobox/combobox.stories.tsx
  packages/admin-ui/src/combobox/combobox.style.ts
  packages/admin-ui/src/combobox/index.ts
  packages/admin-ui/src/experimental.ts
Labels: 👻 experimental

#109 feat: create documentation footer
  packages/admin-ui-docs/docusaurus.config.js
  packages/admin-ui-docs/src/css/custom.scss
  packages/admin-ui-docs/src/css/sidebar.scss
  packages/admin-ui-docs/src/theme/Footer/index.js
  packages/admin-ui-docs/src/theme/Footer/styles.module.scss
Labels: 📚 documentation
