Repository vtex/shoreline, pull requests merged in 2022-05, with the labels that each got.

#165 feat(radio): add Radio and RadioGroup codemod
  packages/admin-ui-codemod/bin/cli.js
  packages/admin-ui-codemod/src/__tests__/radio-review.test.js
  packages/admin-ui-codemod/src/radio-review.js
Labels: 🆕 feature

#181 fix(font): update VTEX Trust version
  packages/admin-ui-core/src/tokens/text.ts
  packages/admin-ui-core/src/values/typography.ts
  packages/admin-ui-docs/src/css/custom.scss
  packages/admin-ui-docs/static/VTEXTrust-VF-May-5-2022.woff2
  packages/admin-ui-react/src/system/create-system.tsx
  packages/admin-ui/src/abbr/__snapshots__/abbr.test.tsx.snap
  packages/admin-ui/src/button/__snapshots__/button.test.tsx.snap
  packages/admin-ui/src/components/AbstractInput/__snapshots__/AbstractInput.test.tsx.snap
  packages/admin-ui/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
  packages/admin-ui/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/admin-ui/src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  packages/admin-ui/src/components/Collapsible/__tests__/__snapshots__/Collapsible.test.tsx.snap
  packages/admin-ui/src/components/CollapsibleGroup/__snapshots__/CollapsibleGroup.test.tsx.snap
  packages/admin-ui/src/components/DataView/__tests__/__snapshots__/DataViewStatus.test.tsx.snap
  packages/admin-ui/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/admin-ui/src/components/FilterBar/__tests__/__snapshots__/FilterBar.test.tsx.snap
  packages/admin-ui/src/components/Heading/__snapshots__/Heading.test.tsx.snap
  packages/admin-ui/src/components/Input/__snapshots__/Input.test.tsx.snap
  packages/admin-ui/src/components/InputPassword/__snapshots__/InputPassword.test.tsx.snap
  packages/admin-ui/src/components/Label/__snapshots__/Label.test.tsx.snap
  packages/admin-ui/src/components/List/__snapshots__/List.test.tsx.snap
  packages/admin-ui/src/components/Menu/__snapshots__/Menu.test.tsx.snap
  packages/admin-ui/src/components/NumericStepper/__snapshots__/NumericStepper.test.tsx.snap
  packages/admin-ui/src/components/Page/__tests__/__snapshots__/PageHeader.test.tsx.snap
  packages/admin-ui/src/components/Paragraph/__snapshots__/Paragraph.test.tsx.snap
  packages/admin-ui/src/components/Search/__tests__/__snapshots__/Search.test.tsx.snap
  packages/admin-ui/src/components/Select/__snapshots__/Select.test.tsx.snap
  packages/admin-ui/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
  packages/admin-ui/src/components/Tag/__snapshots__/Tag.test.tsx.snap
  packages/admin-ui/src/components/Text/__snapshots__/Text.test.tsx.snap
  packages/admin-ui/src/components/TextArea/__snapshots__/TextArea.test.tsx.snap
  packages/admin-ui/src/components/Toast/__tests__/__snapshots__/Toast.test.tsx.snap
  packages/admin-ui/src/filters/__tests__/__snapshots__/filter-multiple.test.tsx.snap
  packages/admin-ui/src/filters/__tests__/__snapshots__/filter.test.tsx.snap
  packages/admin-ui/src/radio/__snapshots__/radio.test.tsx.snap
Labels: 🐛 bug

#186 fix(admin-ui): update focus-ring to the latest specs
  packages/admin-ui-core/src/values/styleKit.ts
  packages/admin-ui/src/button/__snapshots__/button.test.tsx.snap
  packages/admin-ui/src/components/AbstractInput/__snapshots__/AbstractInput.test.tsx.snap
  packages/admin-ui/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  packages/admin-ui/src/components/Collapsible/__tests__/__snapshots__/Collapsible.test.tsx.snap
  packages/admin-ui/src/components/CollapsibleGroup/__snapshots__/CollapsibleGroup.test.tsx.snap
  packages/admin-ui/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/admin-ui/src/components/FilterBar/__tests__/__snapshots__/FilterBar.test.tsx.snap
  packages/admin-ui/src/components/Input/__snapshots__/Input.test.tsx.snap
  packages/admin-ui/src/components/InputPassword/__snapshots__/InputPassword.test.tsx.snap
  packages/admin-ui/src/components/Menu/__snapshots__/Menu.test.tsx.snap
  packages/admin-ui/src/components/NumericStepper/__snapshots__/NumericStepper.test.tsx.snap
  packages/admin-ui/src/components/Page/__tests__/__snapshots__/PageHeader.test.tsx.snap
  packages/admin-ui/src/components/Search/__tests__/__snapshots__/Search.test.tsx.snap
  packages/admin-ui/src/components/Select/__snapshots__/Select.test.tsx.snap
  packages/admin-ui/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
  packages/admin-ui/src/components/Tag/__snapshots__/Tag.test.tsx.snap
  packages/admin-ui/src/components/TextArea/__snapshots__/TextArea.test.tsx.snap
  packages/admin-ui/src/components/Toast/__tests__/__snapshots__/Toast.test.tsx.snap
  packages/admin-ui/src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
  packages/admin-ui/src/filters/__tests__/__snapshots__/filter-multiple.test.tsx.snap
  packages/admin-ui/src/filters/__tests__/__snapshots__/filter.test.tsx.snap
  packages/admin-ui/src/radio/__snapshots__/radio.test.tsx.snap
Labels: 🐛 bug

#162 NAD-861 - Switch component review
  packages/admin-ui-codemod/bin/cli.js
  packages/admin-ui-codemod/src/__tests__/toggle-to-switch.test.js
  packages/admin-ui-codemod/src/toggle-to-switch.js
  packages/admin-ui-core/src/tokens/bg.ts
  packages/admin-ui-core/src/tokens/fg.ts
  packages/admin-ui-core/src/types.ts
  packages/admin-ui-core/src/values/styleKit.ts
  packages/admin-ui-docs/docs/guidelines/components/switch.mdx
  packages/admin-ui-docs/docs/guidelines/components/toggle.mdx
  packages/admin-ui/src/components/Toggle/Toggle.stories.tsx
  packages/admin-ui/src/components/Toggle/Toggle.style.ts
  packages/admin-ui/src/components/Toggle/Toggle.test.tsx
  packages/admin-ui/src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
  packages/admin-ui/src/components/Toggle/index.tsx
  packages/admin-ui/src/index.ts
  packages/admin-ui/src/switch/__snapshots__/switch.test.tsx.snap
  packages/admin-ui/src/switch/index.ts
  packages/admin-ui/src/switch/message.tsx
  packages/admin-ui/src/switch/switch-button.tsx
  packages/admin-ui/src/switch/switch.stories.tsx
  packages/admin-ui/src/switch/switch.style.ts
  packages/admin-ui/src/switch/switch.test.tsx
  packages/admin-ui/src/switch/switch.tsx
  packages/admin-ui/src/switch/types.ts
  packages/formik/src/components/FormikToggle/FormikToggle.test.tsx
  packages/formik/src/components/FormikToggle/canvas.stories.tsx
  packages/formik/src/components/FormikToggle/index.tsx
Labels: 📚 documentation, 🧹 refactoring, 🧪 tests, 🚨 breaking change

#189 feat(admin-ui-form): create library w/ form & watch features
  packages/admin-ui-form/LICENSE
  packages/admin-ui-form/package.json
  packages/admin-ui-form/src/form/form.state.ts
  packages/admin-ui-form/src/form/form.ts
  packages/admin-ui-form/src/form/index.ts
  packages/admin-ui-form/src/form/stories/form.stories.tsx
  packages/admin-ui-form/src/index.ts
  packages/admin-ui-form/src/watch/index.ts
  packages/admin-ui-form/src/watch/stories/watch.stories.tsx
  packages/admin-ui-form/src/watch/use-watch.ts
  packages/admin-ui-form/src/watch/watch.tsx
  yarn.lock
Labels: 🆕 feature, 👻 experimental

#193 fix(text-input): a11y, spaces, and next terminology
  packages/admin-ui/src/checkbox/__snapshots__/checkbox.test.tsx.snap
  packages/admin-ui/src/filters/__tests__/__snapshots__/filter-multiple.test.tsx.snap
  packages/admin-ui/src/form-control/__snapshots__/form-control.test.tsx.snap
  packages/admin-ui/src/form-control/form-control-message.tsx
  packages/admin-ui/src/form-control/form-control.tsx
  packages/admin-ui/src/index.ts
  packages/admin-ui/src/next.ts
  packages/admin-ui/src/radio/__snapshots__/radio.test.tsx.snap
  packages/admin-ui/src/switch/__snapshots__/switch.test.tsx.snap
  packages/admin-ui/src/text-input/text-input.style.ts
  packages/admin-ui/src/text-input/text-input.tsx
Labels: 🐛 bug, 🚨 breaking change, ♿️ a11y

#192 Admin UI Form: Integrate text-input & improve validation rules
  packages/admin-ui-form/package.json
  packages/admin-ui-form/src/form/form.state.ts
  packages/admin-ui-form/src/form/stories/form.stories.tsx
  packages/admin-ui-form/src/index.ts
  packages/admin-ui-form/src/resolvers/index.ts
  packages/admin-ui-form/src/resolvers/stories/yup.stories.tsx
  packages/admin-ui-form/src/resolvers/yup.ts
  packages/admin-ui-form/src/text-input/index.ts
  packages/admin-ui-form/src/text-input/stories/text-input.stories.tsx
  packages/admin-ui-form/src/text-input/text-input.tsx
  packages/admin-ui-form/src/util/dx.ts
  packages/admin-ui-form/src/util/error.ts
  packages/admin-ui-form/src/util/index.ts
  packages/admin-ui-form/src/watch/use-watch.ts
  yarn.lock
Labels: 👻 experimental

#174 feat(search): add Search component review
  packages/admin-ui-docs/docs/guidelines/components/search.mdx
  packages/admin-ui-docs/src/components/FilterDataGrid/index.tsx
  packages/admin-ui-docs/src/components/IconsGrid/index.tsx
  packages/admin-ui-docs/src/components/IconsPage.tsx
  packages/admin-ui-docs/src/theme/Root.js
  packages/admin-ui/src/components/DataGrid/__stories__/dataview.stories.tsx
  packages/admin-ui/src/components/Page/__stories__/Page.stories.tsx
  packages/admin-ui/src/components/Search/Search.style.ts
  packages/admin-ui/src/components/Search/Search.tsx
  packages/admin-ui/src/components/Search/__stories__/Search.stories.tsx
  packages/admin-ui/src/components/Search/__tests__/Search.test.tsx
  packages/admin-ui/src/components/Search/__tests__/__snapshots__/Search.test.tsx.snap
  packages/admin-ui/src/components/Search/hooks/useSearchState.ts
  packages/admin-ui/src/index.ts
  packages/admin-ui/src/search/__snapshots__/search.test.tsx.snap
  packages/admin-ui/src/search/hooks/useQuerySearchState.ts
  packages/admin-ui/src/search/hooks/useSearchState.ts
  packages/admin-ui/src/search/index.tsx
  packages/admin-ui/src/search/search.i18n.ts
  packages/admin-ui/src/search/search.stories.tsx
  packages/admin-ui/src/search/search.style.ts
  packages/admin-ui/src/search/search.test.tsx
  packages/admin-ui/src/search/search.tsx
Labels: 📚 documentation, 🆕 feature
