Repository vtex/shoreline, pull requests merged in 2022-04, with the labels that each got.

#120 feat(inline): promote component
  packages/admin-ui-core/src/types.ts
  packages/admin-ui-docs/docs/guidelines/components/inline.mdx
  packages/admin-ui-docs/docs/guidelines/experimental/bleed.mdx
  packages/admin-ui/src/experimental.ts
  packages/admin-ui/src/index.ts
  packages/admin-ui/src/inline/inline.stories.tsx
  packages/admin-ui/src/inline/inline.tsx
Labels: 🆕 feature, 👻 experimental

#123 Feat/nad 1019
  packages/admin-ui-docs/docs/guidelines/components/alert.mdx
  packages/admin-ui-docs/src/components/Page/Panel.tsx
  packages/admin-ui-docs/src/components/Page/index.tsx
  packages/admin-ui-docs/src/components/Page/styles.scss
Labels: 📚 documentation

#92 Refactor admin-ui react
  packages/admin-ui-react/package.json
  packages/admin-ui-react/src/__stories__/jsx.stories.tsx
  packages/admin-ui-react/src/__stories__/system.stories.tsx
  packages/admin-ui-react/src/__stories__/tag.stories.tsx
  packages/admin-ui-react/src/__tests__/create-system.test.tsx
  packages/admin-ui-react/src/__tests__/jsx.test.tsx
  packages/admin-ui-react/src/__tests__/setup.ts
  packages/admin-ui-react/src/__tests__/tag.test.tsx
  packages/admin-ui-react/src/__tests__/use-media-query.test.tsx
  packages/admin-ui-react/src/__tests__/use-stylesheet.test.ts
  packages/admin-ui-react/src/__tests__/util.test.ts
  packages/admin-ui-react/src/__tests__/util.test.tsx
  packages/admin-ui-react/src/context.ts
  packages/admin-ui-react/src/hooks/index.ts
  packages/admin-ui-react/src/hooks/use-media-query.ts
  packages/admin-ui-react/src/hooks/use-responsive-value.ts
  packages/admin-ui-react/src/hooks/useStoredState.ts
  packages/admin-ui-react/src/index.ts
  packages/admin-ui-react/src/index.tsx
  packages/admin-ui-react/src/system-deprecated/dom-elements.ts
  packages/admin-ui-react/src/system-deprecated/index.ts
  packages/admin-ui-react/src/system-deprecated/jsx.tsx
  packages/admin-ui-react/src/system-deprecated/symbols.ts
  packages/admin-ui-react/src/system-deprecated/tag.tsx
  packages/admin-ui-react/src/system-deprecated/types.ts
  packages/admin-ui-react/src/system-deprecated/use-stylesheet.ts
  packages/admin-ui-react/src/system-deprecated/util.ts
  packages/admin-ui-react/src/system/context.ts
  packages/admin-ui-react/src/system/create-system.tsx
  packages/admin-ui-react/src/system/icons.tsx
  packages/admin-ui-react/src/system/index.ts
  packages/admin-ui-react/src/system/system.tsx
  packages/admin-ui-react/src/system/types.ts
  packages/admin-ui-react/src/themeMode.tsx
  packages/admin-ui-react/src/util.ts
  packages/admin-ui-react/typings/vtex.phosphor.d.ts
  packages/admin-ui/src/components/Sidebar/components/SidebarGroup.tsx
  packages/admin-ui/src/types.ts
  yarn.lock
Labels: 🧹 refactoring

#134 fix(codemod): fix imports and engines
  packages/admin-ui-codemod/bin/admin-ui-codemod.js
  packages/admin-ui-codemod/package.json
Labels: 🐛 bug

#127 NAD-1035 - Toast: expose `csx` props
  packages/admin-ui/src/components/Toast/__stories__/Toast.stories.tsx
  packages/admin-ui/src/components/Toast/components/Toast.tsx
  packages/admin-ui/src/components/Toast/types.ts
Labels: 🆕 feature

#132 Feat/nad 1058 code section
  packages/admin-ui-docs/src/components/CodeBlockWrapper/CodeBlockWrapper.tsx
  packages/admin-ui-docs/src/components/CodeBlockWrapper/components/ToggleCodeButton.tsx
  packages/admin-ui-docs/src/components/CodeBlockWrapper/index.ts
  packages/admin-ui-docs/src/components/CodeBlockWrapper/useCollapsibleCodeBlock.tsx
  packages/admin-ui-docs/src/components/CodeBlockWrapper/useCopyCodeBlock.tsx
  packages/admin-ui-docs/src/components/CodePreviewContainer/index.tsx
  packages/admin-ui-docs/src/components/CodePreviewContainer/styles.scss
  packages/admin-ui-docs/src/components/CodeSection/index.tsx
  packages/admin-ui-docs/src/components/MultipleCodeSection/index.tsx
  packages/admin-ui-docs/src/components/MultipleCodeSection/styles.scss
  packages/admin-ui-docs/src/components/PageSection/index.tsx
  packages/admin-ui-docs/src/components/PageSection/styles.scss
  packages/admin-ui-docs/src/css/custom.scss
  packages/admin-ui-docs/src/theme/CodeBlock/CustomCodeBlock.js
  packages/admin-ui-docs/src/theme/CodeBlock/styles.module.css
  packages/admin-ui-docs/src/theme/CodeBlock/styles.module.scss
  packages/admin-ui-docs/src/theme/Playground/index.js
  packages/admin-ui-docs/src/theme/Playground/styles.module.scss
  packages/admin-ui-docs/tsconfig.json
Labels: 📚 documentation

#133 Refactor/update button page
  packages/admin-ui-docs/docs/guidelines/components/button.mdx
  packages/admin-ui-docs/src/theme/CodeBlock/styles.module.scss
Labels: 📚 documentation

#150 NAD-1095 docs(toggle): add design ref tab
  packages/admin-ui-docs/docs/guidelines/components/toggle.mdx
Labels: 📚 documentation

#141 docs(checkbox): add design reference tab
  packages/admin-ui-docs/docs/guidelines/components/checkbox.mdx
Labels: 📚 documentation

#138 NAD-1081 docs(card): add design reference tab
  packages/admin-ui-docs/docs/guidelines/components/alert.mdx
  packages/admin-ui-docs/docs/guidelines/components/card.mdx
  packages/admin-ui-docs/docs/guidelines/components/select.mdx
Labels: 📚 documentation

#139 NAD-1084 docs(datepicker): add design reference tab
  packages/admin-ui-docs/docs/guidelines/experimental/date-picker.mdx
Labels: 📚 documentation

#142 NAD-1086 docs(anchor): add design ref tab
  packages/admin-ui-docs/docs/guidelines/components/anchor.mdx
Labels: 📚 documentation

#145 NAD-1090 docs(numeric stepper): add design ref tab
  packages/admin-ui-docs/docs/guidelines/components/numeric-stepper.mdx
Labels: 📚 documentation

#147 NAD-1092 docs(tag): add design ref tab
  packages/admin-ui-docs/docs/guidelines/components/tag.mdx
Labels: 📚 documentation

#148 NAD-1093 docs(textarea): add design ref tab
  packages/admin-ui-docs/docs/guidelines/components/text-area.mdx
Labels: 📚 documentation

#149 NAD-1094 docs(toast): add design ref tab
  packages/admin-ui-docs/docs/guidelines/components/toast.mdx
Labels: 📚 documentation

#153 NAD-1096 docs(tooltip): add design ref tab
  packages/admin-ui-docs/docs/guidelines/components/tooltip.mdx
Labels: 📚 documentation

#154 NAD-1089 docs(select): add design ref tab
  packages/admin-ui-docs/docs/guidelines/components/select.mdx
Labels: 📚 documentation

#155 NAD-1082 Feature/button design ref
  packages/admin-ui-docs/docs/guidelines/components/button.mdx
Labels: 📚 documentation

#159 docs(best-practices): add BestPractices component
  packages/admin-ui-docs/docs/guidelines/components/button.mdx
  packages/admin-ui-docs/src/components/BestPractices.tsx
  packages/admin-ui-docs/src/theme/CodeBlock/index.js
  packages/admin-ui-docs/src/theme/Playground/index.js
  packages/admin-ui-docs/src/theme/Playground/styles.module.scss
Labels: 📚 documentation
