Repository vtex/shoreline, pull requests merged in 2024-09, with the labels that each got.

#1936 (docs): Include icon synonyms
  packages/docs/components/icons-grid/icons.ts
Labels: documentation

#1960 fix(drawer): Figma design
  packages/shoreline/src/components/drawer/drawer-dismiss.tsx
  packages/shoreline/src/components/drawer/drawer-heading.tsx
  packages/shoreline/src/components/drawer/drawer-popover.tsx
  packages/shoreline/src/themes/sunrise/components/drawer.css
Labels: design

#1965 fix(drawer): fix layout shift
  packages/docs/pages/components/drawer.mdx
  packages/docs/pages/components/drawer/_meta.json
  packages/docs/public/assets/all-drawer.png
  packages/shoreline/package.json
  packages/shoreline/src/themes/sunrise/components/drawer.css
  pnpm-lock.yaml
Labels: bug

#1961 docs: adds callout in the how to contribute page
  packages/docs/pages/guides/how-to-contribute.mdx
Labels: documentation
